name: Test Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Test step
        run: |
          echo "🎉 ¡GitHub Actions funciona correctamente!"
          echo "Fecha y hora: $(date)"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Branch: ${{ github.ref_name }}"
          
      - name: Show directory structure
        run: |
          echo "Estructura del proyecto:"
          find . -type f -name "*.yml" -o -name "*.yaml" -o -name "Dockerfile" | head -10 